### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Jumpstyle135** [Acquized/ProjectRetile#5]
No permission available... What is permission ?

**Comment by Acquized** [comment]
Command | Permission | What it does
------------ | ----------------- | -----------------
/reportinfo | projectretile.commands.reportinfo | Lists Information about a Report with a required Token
/listreports | projectretile.commands.listreports | Lists all Reports in a Gui
/waitingqueue | projectretile.commands.queue | Lists all Reports that are in the Waiting Queue in a Gui. Once executed all Waiting Reports get moved to normal Reports
/report | projectretile.commands.report | Submites a Report
/retile | projectretile.general | General Command
Enable/Disable Debug (/retile debug) | projectretile.general.debug
Reload Config (/retile reload) | projectretile.general.reload
/togglereports | projectretile.commands.togglereports | Toggles receiving of Reports 
 | projectretile.blacklist.bypass | Bypass Blacklist
 | projectretile.report.receive | Required for a Notification to receive when somebody submites a Report
 | projectretile.report.receive.offline | Required for a Join Notification if Reports have been submited offline

Also, please open next time **one** Issue asking all Questions for better visibility.
